backend:
  name: git-gateway
  branch: main # Branch to update (master by default)
  squash_merges: true

# This line should *not* be indented
publish_mode: editorial_workflow

media_folder: "images/post/" # Folder where user uploaded files should go
site_url: https://navigate.rsamdio.org
display_url: navigate.rsamdio.org
logo_url: https://navigate.rsamdio.org/images/logo.png

collections: # A list of collections the CMS should be able to edit 
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{date}}-{{slug}}" # {{year}}-{{month}}-{{day}}-{{slug}}
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Date"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        picker_utc: true
      - label: "Author"
        name: author
        widget: object
        fields:
          - {label: "Author Name", name: "name", widget: "string"}
          - {label: "Author Bio Link", name: "biolink", widget: "string"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["DRR-Access,Club-Leader-Access"]
      - label: "CTA Buttons"
        name: buttons
        widget: list
        fields:
          - {label: "CTA Button Text", name: "text", widget: "string"}
          - {label: "CTA Button Link", name: "link", widget: "string"}
      - {label: "Embed URL", name: "embedurl", widget: "string"}
      - label: "Thumbnails"
        name: "images"
        widget: "list"
        fields:
          - {label: "Image", name: "imglink", widget: "image"}      
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
